name: 🔒 Security Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '18'

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  # ==========================================
  # Job 1: Dependency Vulnerability Scan
  # ==========================================
  dependency-scan:
    name: 🔍 Dependency Vulnerability Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔍 Run npm audit
        run: |
          npm audit --audit-level moderate --json > npm-audit.json || true

      - name: 📊 Upload npm audit results
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-results
          path: npm-audit.json

      - name: 🛡️ Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json > snyk-results.json

      - name: 📊 Upload Snyk results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-results
          path: snyk-results.json

  # ==========================================
  # Job 2: SAST (Static Application Security Testing)
  # ==========================================
  sast-scan:
    name: 🔍 SAST Code Analysis
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: 🏗️ Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: 🔍 Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:javascript'
        continue-on-error: true

      - name: 🛡️ Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten
            p/nodejs
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        continue-on-error: true

  # ==========================================
  # Job 3: Secret Scanning
  # ==========================================
  secret-scan:
    name: 🔐 Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 TruffleHog OSS Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        continue-on-error: true
        if: github.event_name != 'push' || github.event.before != '0000000000000000000000000000000000000000'

      - name: 🔍 GitLeaks Secret Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  # ==========================================
  # Job 4: Security Report Summary
  # ==========================================
  security-summary:
    name: 📋 Security Summary Report
    runs-on: ubuntu-latest
    needs: [dependency-scan, sast-scan, secret-scan]
    if: always()

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 📥 Download all artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true

      - name: 📋 Generate Security Summary
        run: |
          echo "# 🔒 Security Scan Summary" > security-summary.md
          echo "" >> security-summary.md
          echo "## 📊 Scan Results" >> security-summary.md
          echo "" >> security-summary.md

          echo "| Category | Status |" >> security-summary.md
          echo "|----------|--------|" >> security-summary.md

          # Check each job status
          if [ "${{ needs.dependency-scan.result }}" == "success" ]; then
            echo "| Dependency Scan | ✅ PASS |" >> security-summary.md
          else
            echo "| Dependency Scan | ⚠️ CHECK |" >> security-summary.md
          fi

          if [ "${{ needs.sast-scan.result }}" == "success" ]; then
            echo "| SAST Analysis | ✅ PASS |" >> security-summary.md
          else
            echo "| SAST Analysis | ⚠️ CHECK |" >> security-summary.md
          fi

          if [ "${{ needs.secret-scan.result }}" == "success" ]; then
            echo "| Secret Detection | ✅ PASS |" >> security-summary.md
          else
            echo "| Secret Detection | ⚠️ CHECK |" >> security-summary.md
          fi

          echo "" >> security-summary.md
          echo "Generated on: $(date)" >> security-summary.md

      - name: 📊 Upload Security Summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.md
